import 'package:cocoon/res/constants/imports.dart';

class CurrencyController extends GetxController{
  List currencyList = [
    "US Dollar (USD)",
    "Euro (EUR)",
    "Japanese Yen (JPY)",
    "British Pound (GBP)",
    "Australian Dollar (AUD)",
    "Canadian Dollar (CAD)",
    "Swiss Franc (CHF)",
    "Chinese Yuan (CNY)",
    "Swedish Krona (SEK)",
    "New Zealand Dollar (NZD)",
    "Mexican Peso (MXN)",
    "Singapore Dollar (SGD)",
    "Hong Kong Dollar (HKD)",
    "Norwegian Krone (NOK)",
    "South Korean Won (KRW)",
    "Turkish Lira (TRY)",
    "Indian Rupee (INR)",
    "Brazilian Real (BRL)",
    "South African Rand (ZAR)",
    "Philippine Peso (PHP)",
    "Czech Koruna (CZK)",
    "Indonesian Rupiah (IDR)",
    "Malaysian Ringgit (MYR)",
    "Hungarian Forint (HUF)",
    "Icelandic Krona (ISK)",
    "Colombian Peso (COP)",
    "Thai Baht (THB)",
    "Polish Złoty (PLN)",
    "Danish Krone (DKK)",
    "Saudi Riyal (SAR)",
    "Israeli Shekel (ILS)",
    "Argentine Peso (ARS)",
    "Chilean Peso (CLP)",
    "United Arab Emirates Dirham (AED)",
    "Qatari Riyal (QAR)",
    "Egyptian Pound (EGP)",
    "Pakistani Rupee (PKR)",
    "Vietnamese Dong (VND)",
    "Kuwaiti Dinar (KWD)"
  ];
}